#!/bin/bash

count=0

while [ $count -le 100 ] 
do
	./aco-r -archive 50 -ants 50 -iterations 1000 -rho 1.0 -rnd $RANDOM >> aco-r-runs.dat &
	./aco-r -archive 50 -ants 50 -iterations 1000 -rho 1.0 -rnd $RANDOM >> aco-r-runs.dat
        count=$[$count+1]
done
